from . import test_vat_declaration
from . import test_mis_menus
from . import test_itvair
from . import test_adv_bar_hotel_year
from . import test_adv_declaration_sequence
from . import test_adv_withholding_mixed
from . import test_adv_multi_company
from . import test_adv_closing_lifecycle
from . import test_adv_volume
